// first try -> followed the directions from the link below exactly - the commented out sections are what I added
// courtesy of http://www.codeproject.com/Articles/412511/Simple-client-server-network-using-Cplusplus-and-W

#ifndef LOGIN_PACKET_H
#define LOGIN_PACKET_H


#pragma once

#include "stdafx.h"


enum LoginPacketTypes {

	CHECK_NAME_OLD = 1,
	CHECK_NAME_NEW_VALIDITY = 2,
	CHECK_NAME_PW_CHG = 3,
	CHECK_PASSWORD_OLD = 4,
	CHECK_PASSWORD_NEW_VALIDITY = 5,
	CHECK_PASSWORD_PW_CHG_LOGIN = 6,
	CHECK_PASSWORD_PW_CHG_RECORD = 7,
	ADMIN_LOGIN = 8,
	ADMIN_PW_LOGIN = 9,
	LOGIN_COMPLETE_OLD = 18,
	LOGIN_COMPLETE_NEW = 19,
	CONTINUE = 20,
	DUAL_PROCEED_OLD = 10,
	DUAL_PROCEED_PW_CHG = 11,
	DUAL_PROCEED_ADMIN = 12,
	DUAL_PROCEED_ADMIN2 = 13,
	DUAL_LOCK_OLD = 14,
	DUAL_LOCK_PW_CHG = 15,
	DUAL_LOCK_ADMIN = 16,
	DUAL_LOCK_ADMIN2 = 17,	
	
	CHECK_NAME_NEW_APPROVE = 129,
	INVALID_NAME_OLD = 130,	
	INVALID_NAME_PW_CHG = 132,
	INVALID_NAME_NEW_CONFLICT = 133,	
	CHECK_PASSWORD_PW_CHG_VALIDITY = 135,
	INVALID_PASSWORD_OLD = 136,
	INVALID_PASSWORD_NEW_BADCHAR = 137,
	INVALID_PASSWORD_PW_CHG_LOGIN = 138,
	INVALID_PASSWORD_PW_CHG_BADCHAR = 139,
	INVALID_PASSWORD_NEW_LENGTH = 140,
	INVALID_PASSWORD_PW_CHG_LENGTH = 141,
	INVALID_PASSWORD_NEW_NOMATCH = 142,
	INVALID_PASSWORD_PW_CHG_NOMATCH = 143,
	INVALID_PASSWORD_PW_LOGIN_NOMATCH = 144,
	CHANGE_TO_LOGINMENU = 145,
	CHANGE_TO_ENTRY = 146,
	CHANGE_TO_ADMIN = 147,	
	INVALID_INPUT2 = 149,
	ACCOUNT_LOCK_BEGIN = 150,
	PASSWORD_LOCKED = 151,
	ADMIN_INVALID_NAME = 152,
	ADMIN_INVALID_PW = 153,
	ADMIN_LOG_COMPLETE = 154,
	TO_ADMINMENU = 155,
	ADMIN_INVALID_ENTRY = 156,
	PROCEED = 158,
	DUAL_LOG_OLD = 167,
	DUAL_LOG_PW_CHG = 168,
	DUAL_LOG_ADMIN = 169,
	INVALID_INPUT3 = 170,
	INVALID_INPUT4 = 171,
	INVALID_INPUT5 = 172,
	ADMIN_USER_ACCT_CONFLICT = 173,
	USER_ADMIN_ACCT_CONFLICT = 174,
	LOG_LOCKED = 180,
	SECURITY_LOCKED = 181,
	INVALID_NAME_NEW_NOMATCH = 182,
	LOGIN_SUCCESS_OLD = 184,
	LOGIN_SUCCESS_NEW = 185,
	LOGIN_SUCCESS_PW_CHG = 186,
	ADMIN_LOG_SUCCESS = 187,
	ADMIN_LOGOUT = 188

};

#endif
